from __future__ import annotations

import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
FRONTEND_DIR = REPO_ROOT / "frontend/src/modules/koubo/DanceMimicV1"
ROUTER_SOURCE = REPO_ROOT / "backend/opcrew_backend/koubo/dance_mimic_router.py"
SCHEMAS_SOURCE = REPO_ROOT / "backend/opcrew_backend/koubo/schemas.py"


class DanceMimicOneClickMovieContractTest(unittest.TestCase):
    def test_frontend_exposes_one_click_movie_button_and_status_dialog(self) -> None:
        module_source = (FRONTEND_DIR / "DanceMimicV1Module.jsx").read_text(encoding="utf-8")
        api_source = (FRONTEND_DIR / "danceMimicV1Api.js").read_text(encoding="utf-8")
        dialog_source = (FRONTEND_DIR / "OneClickMovieDialog.jsx").read_text(encoding="utf-8")
        css_source = (FRONTEND_DIR / "danceMimicV1.css").read_text(encoding="utf-8")

        self.assertIn("一键成片", module_source)
        self.assertIn("startOneClickMovie", module_source)
        self.assertIn("latest_movie_run", module_source)
        self.assertIn("const fullMovieSteps = createMemo(() => [...steps(), ...movieSteps()]);", module_source)
        self.assertIn('"05_01": "生成视频计划"', module_source)
        self.assertIn('"05_02": "逐句生成视频"', module_source)
        self.assertIn('"06_01": "合并成片"', module_source)
        self.assertNotIn('"05_01": "05-01', module_source)
        self.assertNotIn('"05_02": "05-02', module_source)
        self.assertNotIn('"06_01": "06-01', module_source)
        self.assertIn('onClick={() => setMovieDialogOpen(true)} title={readyForStoryBoard() ? "打开一键成片运行弹窗" : "故事版生成后可一键成片"}', module_source)
        self.assertIn("onStart={() => void startOneClickMovie({ force: true })}", module_source)
        self.assertIn("import OneClickMovieDialog", module_source)
        self.assertIn("<OneClickMovieDialog", module_source)
        self.assertIn("steps={fullMovieSteps()}", module_source)
        self.assertIn("segments={movieSegments()}", module_source)
        self.assertIn('run_only_step_id: String(runOptions.run_only_step_id || "")', module_source)
        self.assertIn('run_from_step_id: String(runOptions.run_from_step_id || "")', module_source)
        self.assertIn('await startOneClickMovie({ force: false, resume: true, run_only_step_id: "05_02" });', module_source)
        self.assertIn('await startOneClickMovie({ force: false, resume: true, run_from_step_id: "05_02" });', module_source)
        self.assertIn("onResumeVideoStep={() => void resumeOneClickMovieVideoStep()}", module_source)
        self.assertIn("onResumeVideoStepAndFollowing={() => void resumeOneClickMovieFromVideoStep()}", module_source)
        self.assertIn("STEP_LABELS[step.id] || ONE_CLICK_STEP_LABELS[step.id]", module_source)
        self.assertIn('import { Portal } from "solid-js/web";', dialog_source)
        self.assertIn("function taskToneFromStatus", dialog_source)
        self.assertIn("const [stepsExpanded, setStepsExpanded] = createSignal(false);", dialog_source)
        self.assertIn("const [segmentsExpanded, setSegmentsExpanded] = createSignal(false);", dialog_source)
        self.assertIn("const [stepMenu, setStepMenu] = createSignal(null);", dialog_source)
        self.assertIn("function weightedStepProgress", dialog_source)
        self.assertIn("const stepProgressPercent = createMemo(() => weightedStepProgress(steps()));", dialog_source)
        self.assertIn("全流程进度", dialog_source)
        self.assertIn('aria-expanded={stepsExpanded()}', dialog_source)
        self.assertIn("<Show when={!stepsExpanded()} fallback=", dialog_source)
        self.assertIn("dmv1-movie-step-expanded", dialog_source)
        self.assertIn(">收起</button>", dialog_source)
        self.assertIn("function openStepContextMenu", dialog_source)
        self.assertIn('String(step?.id || "") !== "05_02"', dialog_source)
        self.assertIn("onContextMenu={(event) => openStepContextMenu(event, step)}", dialog_source)
        self.assertIn("继续完成该步", dialog_source)
        self.assertIn("继续完成后续步骤", dialog_source)
        self.assertIn("<Portal>", dialog_source)
        self.assertIn("setDialogPosition({ left: rect.left, top: rect.top });", dialog_source)
        self.assertIn('classList={{ "is-dragged": Boolean(dialogPosition()) }}', dialog_source)
        self.assertNotIn('transform: "none"', dialog_source)
        self.assertIn('aria-expanded={segmentsExpanded()}', dialog_source)
        self.assertIn("onClick={() => setSegmentsExpanded((value) => !value)}", dialog_source)
        self.assertIn("<Show when={segmentsExpanded()}>", dialog_source)
        self.assertIn("<b>{index() + 1}</b>", dialog_source)
        self.assertIn('"completed_working"', dialog_source)
        self.assertIn('segment?.files?.[fileKey]?.exists) return { tone: "done"', dialog_source)
        self.assertIn("storyboardItem?.audio?.exists || storyboardItem?.audio?.path", dialog_source)
        self.assertIn("<TaskBadge state={audioState(segment, storyboardItem)} icon={MicIcon} label=\"音频\" />", dialog_source)
        self.assertIn("function frameLabel", dialog_source)
        self.assertIn("segment?.image_step_label || segment?.first_frame?.image_step_label", dialog_source)
        self.assertIn("first_frame_source_type", dialog_source)
        self.assertNotIn("Number(segment?.index || 0) > 1", dialog_source)
        self.assertIn('"尾帧"', dialog_source)
        self.assertIn("<TaskBadge state={frameState(segment)} icon={ImageIcon} label={frameLabel(segment)} />", dialog_source)
        self.assertIn("<TaskBadge state={videoState(segment)} icon={ClapperboardIcon} label=\"新视频\" />", dialog_source)
        self.assertIn("function syncLabel(segment, props)", dialog_source)
        self.assertIn('title: `等待${syncLabel(segment, props)}`', dialog_source)
        self.assertIn("<TaskBadge state={syncState(segment, props)} icon={AudioLinesIcon} label={syncLabel(segment, props)} />", dialog_source)
        self.assertIn("逐句成片状态", dialog_source)
        self.assertNotIn("<small>{props.outputVideo}</small>", dialog_source)
        self.assertIn(".dmv1-movie-dialog", css_source)
        self.assertIn(".verify-dialog.dmv1-movie-dialog.is-dragged", css_source)
        self.assertIn("z-index: 330 !important", css_source)
        self.assertIn(".dmv1-movie-section-toggle", css_source)
        self.assertIn(".dmv1-movie-flow-status", css_source)
        self.assertIn(".dmv1-movie-progress-track", css_source)
        self.assertIn(".dmv1-movie-step-expanded", css_source)
        self.assertIn(".dmv1-movie-inline-collapse", css_source)
        self.assertIn(".dmv1-movie-context-menu", css_source)
        self.assertIn(".dmv1-movie-task-badge.is-done", css_source)
        self.assertIn("/api/dance-mimic-v1/tasks/${taskId}/one-click-movie", api_source)

    def test_backend_orchestrates_05_01_05_02_06_01_with_hard_contracts(self) -> None:
        router_source = ROUTER_SOURCE.read_text(encoding="utf-8")
        schemas_source = SCHEMAS_SOURCE.read_text(encoding="utf-8")

        self.assertIn("DanceMimicOneClickMoviePayload", schemas_source)
        self.assertIn("run_only_step_id: str = \"\"", schemas_source)
        self.assertIn("run_from_step_id: str = \"\"", schemas_source)
        self.assertIn('"audio": media_preview_entry(workspace, audio_path)', router_source)
        self.assertIn("05_01_VideoPlanGenerator.py", router_source)
        self.assertIn("05_02_VideoPlanExecutor.py", router_source)
        self.assertIn("06_01_VideoPlanComposer.py", router_source)
        self.assertIn("--no-execute-lipsync", router_source)
        self.assertIn("--execute-audio-video-sync", router_source)
        self.assertIn('"no_lipsync": True', router_source)
        self.assertIn('"first_frame_policy": "previous_segment_tail_frame"', router_source)
        self.assertIn('"image_step_label": one_click_image_step_label', router_source)
        self.assertIn('"image_input_kind": image_input_kind', router_source)
        self.assertIn("one_click_image_source_type(first_frame, materialize)", router_source)
        self.assertIn("one_click_movie_selected_specs", router_source)
        self.assertIn("mark_one_click_movie_unselected_steps", router_source)
        self.assertIn("reconcile_stale_one_click_movie_state", router_source)
        self.assertIn("原一键成片运行进程已中断", router_source)
        self.assertIn('"tool_status": "abandoned"', router_source)
        self.assertIn('shot_plan_outputs.get("shot_plan_subtitled_video_path")', router_source)
        self.assertIn('shot_plan_outputs.get("shot_plan_video_path")', router_source)
        self.assertIn('run_only_step_id == "05_02"', router_source)
        self.assertIn('run_from_step_id == "05_02"', router_source)
        self.assertIn("ONE_CLICK_MOVIE_TOOL_SPECS[index:]", router_source)
        self.assertIn('"source_image_regeneration": "disabled"', router_source)
        self.assertIn('tasks.get("need_lipsync")', router_source)
        self.assertIn('first_frame.get("source_type")) != "previous_segment_tail_frame"', router_source)
        self.assertIn("/api/dance-mimic-v1/tasks/{task_id}/one-click-movie", router_source)


if __name__ == "__main__":
    unittest.main()
