from __future__ import annotations

import base64
import json
import platform
import re
import shutil
import subprocess
import textwrap
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlencode
from urllib.request import Request, urlopen


NPC_INSTALL_PATH = Path.home() / ".opencode" / "bin" / "npc"
NPC_DOWNLOAD_URL = "https://github.com/ehang-io/nps/releases/download/v0.26.10/darwin_amd64_client.tar.gz"
SESSION_DIRECTORY = str(Path.home())


DEFAULT_INSTALL_SKILL = textwrap.dedent(
    f"""
    Goal: install the NPS npc client on this macOS machine through OpenCode.

    Hard requirements:
    1. Use shell commands only.
    2. Do not modify files in the current repository.
    3. Install path must be `{NPC_INSTALL_PATH}`.
    4. Download source must default to `{NPC_DOWNLOAD_URL}`.
    5. Upstream GitHub only publishes a macOS amd64 client tarball. On Apple Silicon, still use that GitHub asset and verify the installed binary really runs.
    6. If npc is already installed at `{NPC_INSTALL_PATH}` and runs successfully, do not reinstall it.

    Required shell steps:
    - Detect `uname -s` and `uname -m`.
    - Ensure the parent directory of `{NPC_INSTALL_PATH}` exists.
    - Download the GitHub tarball to a temporary file.
    - Extract only the `npc` binary into `{NPC_INSTALL_PATH}`.
    - Run `chmod +x {NPC_INSTALL_PATH}`.
    - Run `{NPC_INSTALL_PATH} --version`.
    - Run `command -v npc || true`.

    Progress output rules:
    - After each completed stage, emit exactly one short line beginning with one of:
      `[detect]`, `[install]`, `[verify]`, `[error]`.
    - Keep each progress line under 160 characters.

    Final output rules:
    - The final line must be exactly `JSON_RESULT=<json>`.
    - The JSON object must contain exactly these keys:
      `ok`, `already_installed`, `install_method`, `command_path`, `version`, `global_install`, `in_path`, `installed_by_opencrew`, `message`, `error`.
    - `command_path` must be the resolved installed npc path when successful.
    - `install_method` must be `github_release` for fresh installs and `existing` if already present.
    - `global_install` is true only when `command -v npc` resolves to the same installed path.
    - `in_path` is true only when `command -v npc` succeeds.
    - `installed_by_opencrew` is true only when the installed path equals `{NPC_INSTALL_PATH}`.
    - If any step fails, still output the final `JSON_RESULT=` line with `ok=false` and a concise `error` string.
    """
).strip()


DEFAULT_RUN_SKILL = textwrap.dedent(
    f"""
    Goal: manage and validate the OpenCrew NPC service using a generated configuration file.

    Hard requirements:
    1. Use shell commands only.
    2. Do not modify repository files.
    3. The installed binary path is `{NPC_INSTALL_PATH}`.
    4. The runtime config is generated by OpenCrew and the service must be launched with `npc -config <path>`.
    5. Validation success means config load succeeded, the server is reachable, handshake is stable, and proxy registration is accepted.

    Required workflow:
    - Confirm the npc binary exists and is executable.
    - Confirm the generated config paths exist.
    - Launch npc with `-config`.
    - Observe the startup log.
    - Distinguish these stages clearly: `config_load`, `server_connect`, `handshake`, `proxy_registration`.
    - If any stage fails, identify the exact failed step and provide a specific `recommended_fix`.

    Expected result fields:
    - `ok`, `available`, `config_path`, `multi_account_path`, `command_path`, `server_addr`, `target_addr`, `server_port`, `failed_step`, `recommended_fix`, `message`, `error`.
    """
).strip()

DEFAULT_UNINSTALL_SKILL = textwrap.dedent(
    f"""
    Goal: uninstall the OpenCrew-managed NPS npc client on this macOS machine through OpenCode.

    Hard requirements:
    1. Use shell commands only.
    2. Only remove `{NPC_INSTALL_PATH}`.
    3. Do not remove any unrelated files.

    Required shell steps:
    - Check whether `{NPC_INSTALL_PATH}` exists.
    - If it exists, remove it.
    - Run `test -e {NPC_INSTALL_PATH} && echo present || echo absent`.
    - Run `command -v npc || true`.

    Progress output rules:
    - Emit short lines prefixed with `[uninstall]`, `[verify]`, or `[error]`.

    Final output rules:
    - The final line must be exactly `JSON_RESULT=<json>`.
    - The JSON object must contain exactly these keys:
      `ok`, `removed`, `removed_paths`, `message`, `error`.
    - `removed_paths` must be an array.
    - If the target file was absent, return `ok=true`, `removed=false`, and an empty `removed_paths` array.
    - If removal fails, return `ok=false` with a concise `error` string.
    """
).strip()


DEFAULT_SKILLS = {
    "install": {"title": "Install NPC", "content": DEFAULT_INSTALL_SKILL},
    "run": {"title": "Run NPC", "content": DEFAULT_RUN_SKILL},
    "uninstall": {"title": "Uninstall NPC", "content": DEFAULT_UNINSTALL_SKILL},
}


def normalize_arch(machine: str) -> str:
    lowered = machine.lower()
    if lowered in {"x86_64", "amd64"}:
        return "amd64"
    if lowered in {"arm64", "aarch64"}:
        return "arm64"
    return lowered or "unknown"


def read_npc_version(command_path: str) -> str | None:
    for args in ([command_path, "--version"], [command_path, "-version"], [command_path, "version"]):
        try:
            completed = subprocess.run(args, capture_output=True, text=True, timeout=8, check=False)
        except Exception:
            continue
        output = (completed.stdout or completed.stderr or "").strip()
        if output:
            return output.splitlines()[0][:200]
    return None


def detect_environment(_: Path) -> dict[str, Any]:
    system = platform.system().lower()
    arch = normalize_arch(platform.machine())
    which_path = shutil.which("npc")
    command_path = which_path or (str(NPC_INSTALL_PATH) if NPC_INSTALL_PATH.exists() else None)
    installed = bool(command_path and Path(command_path).exists())
    version = read_npc_version(command_path) if installed and command_path else None
    resolved = str(Path(command_path).resolve()) if installed and command_path else None
    managed = str(NPC_INSTALL_PATH.resolve())
    in_path = bool(which_path)
    return {
        "platform": "macos" if system == "darwin" else system,
        "arch": arch,
        "brew_available": shutil.which("brew") is not None,
        "managed_path": str(NPC_INSTALL_PATH),
        "command_path": resolved,
        "installed": installed,
        "available": system == "darwin",
        "version": version,
        "install_method": "github_release" if resolved == managed else ("existing" if installed else None),
        "global_install": bool(which_path and Path(which_path).resolve() == NPC_INSTALL_PATH.resolve()),
        "in_path": in_path,
    }


def default_download_url_for(platform_name: str, arch: str) -> str | None:
    if platform_name == "macos" and arch in {"amd64", "arm64"}:
        return NPC_DOWNLOAD_URL
    return None


@dataclass
class SkillResultError(Exception):
    message: str
    payload: dict[str, Any] | None = None


class OpencodeClient:
    def __init__(
        self,
        base_url: str,
        username: str,
        password: str,
        directory: str,
        logger: Callable[[str, str, str], None],
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.directory = directory
        self.logger = logger
        token = base64.b64encode(f"{username}:{password}".encode("utf-8")).decode("ascii")
        self.auth_header = f"Basic {token}"

    def _request(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
        query: dict[str, str] | None = None,
        timeout: int = 120,
    ) -> Any:
        query_string = f"?{urlencode(query)}" if query else ""
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        req = Request(
            f"{self.base_url}{path}{query_string}",
            data=data,
            method=method,
            headers={
                "Authorization": self.auth_header,
                "Content-Type": "application/json",
            },
        )
        with urlopen(req, timeout=timeout) as response:
            raw = response.read().decode("utf-8", errors="ignore")
            if not raw:
                return None
            return json.loads(raw)

    def create_session(self, kind: str) -> str:
        payload = {
            "title": f"OpenCrew NPC {kind.title()}",
            "permission": [
                {"permission": "external_directory", "pattern": f"{NPC_INSTALL_PATH.parent}/*", "action": "allow"},
                {"permission": "external_directory", "pattern": f"{NPC_INSTALL_PATH.parent}/**", "action": "allow"},
            ],
        }
        session = self._request("POST", "/session", payload, query={"directory": self.directory}, timeout=30)
        if not session or "id" not in session:
            raise SkillResultError("Failed to create OpenCode session.")
        return str(session["id"])

    def prompt_async(self, session_id: str, prompt: str) -> None:
        payload = {"parts": [{"type": "text", "text": prompt}]}
        self._request("POST", f"/session/{session_id}/prompt_async", payload, query={"directory": self.directory}, timeout=30)

    def messages(self, session_id: str) -> list[dict[str, Any]]:
        return self._request("GET", f"/session/{session_id}/message", None, query={"directory": self.directory, "limit": "20"}, timeout=30) or []

    def collect_events(self, session_id: str, stop_event: threading.Event) -> None:
        req = Request(f"{self.base_url}/global/event", headers={"Authorization": self.auth_header})
        try:
            with urlopen(req, timeout=600) as response:
                delta_buffers: dict[str, str] = {}
                message_roles: dict[str, str] = {}
                while not stop_event.is_set():
                    raw = response.readline().decode("utf-8", errors="ignore").strip()
                    if not raw or not raw.startswith("data: "):
                        continue
                    try:
                        event = json.loads(raw[6:])
                    except json.JSONDecodeError:
                        continue
                    payload = event.get("payload") or {}
                    kind = payload.get("type")
                    props = payload.get("properties") or {}
                    if kind == "message.updated":
                        info = props.get("info") or {}
                        if info.get("sessionID") == session_id and info.get("id"):
                            message_roles[str(info.get("id"))] = str(info.get("role") or "")
                    if kind == "session.status" and props.get("sessionID") == session_id:
                        status = ((props.get("status") or {}).get("type") or "unknown").strip()
                        self.logger("session", "info", f"[session] {status}")
                    if kind == "session.idle" and props.get("sessionID") == session_id:
                        self.logger("session", "info", "[session] idle")
                    if kind == "message.part.updated":
                        part = props.get("part") or {}
                        if part.get("sessionID") != session_id:
                            continue
                        if message_roles.get(str(part.get("messageID"))) != "assistant":
                            continue
                        part_type = part.get("type")
                        if part_type == "tool":
                            state = part.get("state") or {}
                            status = state.get("status") or "unknown"
                            tool_name = part.get("tool") or "tool"
                            title = state.get("title") or ((state.get("input") or {}).get("description") or "running")
                            self.logger("tool", "info", f"[{tool_name}] {status}: {title}")
                            output = (state.get("output") or "").strip()
                            if output:
                                first = output.splitlines()[0][:180]
                                self.logger("tool", "info", first)
                        elif part_type == "reasoning":
                            text = (part.get("text") or "").strip()
                            if text:
                                first = text.splitlines()[0][:180]
                                self.logger("reasoning", "info", first)
                        elif part_type == "text":
                            text = (part.get("text") or "").strip()
                            if text and not text.startswith("JSON_RESULT="):
                                for line in text.splitlines():
                                    clean = line.strip()
                                    if clean and not clean.startswith("JSON_RESULT="):
                                        self.logger("assistant", "info", clean[:180])
                        elif part_type == "step-start":
                            self.logger("assistant", "info", "[assistant] step started")
                        elif part_type == "step-finish":
                            reason = part.get("reason") or "done"
                            self.logger("assistant", "info", f"[assistant] step finished ({reason})")
                    if kind == "message.part.delta":
                        if props.get("sessionID") != session_id or props.get("field") != "text":
                            continue
                        if message_roles.get(str(props.get("messageID"))) != "assistant":
                            continue
                        part_id = str(props.get("partID"))
                        delta = str(props.get("delta") or "")
                        current = delta_buffers.get(part_id, "") + delta
                        while "\n" in current:
                            line, current = current.split("\n", 1)
                            clean = line.strip()
                            if clean and not clean.startswith("JSON_RESULT="):
                                self.logger("assistant", "info", clean[:180])
                        delta_buffers[part_id] = current
        except Exception as exc:
            if not stop_event.is_set():
                self.logger("error", "error", f"[stream] {exc}")


def _extract_final_json(text: str) -> dict[str, Any]:
    match = re.search(r"JSON_RESULT\s*=\s*(\{.*\})", text, re.S)
    candidates = []
    if match:
        candidates.append(match.group(1))
    stripped = text.strip()
    if stripped.startswith("{") and stripped.endswith("}"):
        candidates.append(stripped)
    fence = re.search(r"```json\s*(\{.*\})\s*```", text, re.S)
    if fence:
        candidates.append(fence.group(1))
    for candidate in candidates:
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            continue
    raise SkillResultError("OpenCode did not return a valid JSON_RESULT payload.", {"raw": text[-2000:]})


def _final_assistant_text(messages: list[dict[str, Any]]) -> str:
    assistants = [item for item in messages if (item.get("info") or {}).get("role") == "assistant"]
    for message in reversed(assistants):
        parts = message.get("parts") or []
        texts = [str(part.get("text") or "") for part in parts if part.get("type") == "text"]
        if texts:
            return "\n".join(texts).strip()
    raise SkillResultError("OpenCode finished without a final assistant text response.")


def ensure_default_skills(skill_repo: Any, now_ms: int) -> None:
    for kind, info in DEFAULT_SKILLS.items():
        existing = skill_repo.get("npc", kind)
        if existing:
            continue
        skill_repo.upsert("npc", kind, info["title"], info["content"], now_ms)


def get_default_skill(kind: str) -> dict[str, str]:
    return DEFAULT_SKILLS[kind]


def execute_skill(
    kind: str,
    content: str,
    data_dir: Path,
    logger: Callable[[str, str, str], None],
    *,
    opencode_base_url: str,
    opencode_username: str,
    opencode_password: str,
) -> tuple[dict[str, Any], str]:
    if not opencode_base_url.strip() or not opencode_username.strip() or not opencode_password.strip():
        raise SkillResultError("OpenCode connection is incomplete. Finish Step 1 before running NPC tasks.")

    client = OpencodeClient(
        base_url=opencode_base_url,
        username=opencode_username,
        password=opencode_password,
        directory=SESSION_DIRECTORY,
        logger=logger,
    )
    logger("plan", "info", f"Executing {kind}-npc skill through OpenCode")
    session_id = client.create_session(kind)
    stop_event = threading.Event()
    stream_thread = threading.Thread(target=client.collect_events, args=(session_id, stop_event), daemon=True)
    stream_thread.start()
    try:
        client.prompt_async(session_id, content)
        deadline = time.time() + 600
        while time.time() < deadline:
            messages = client.messages(session_id)
            assistants = [item for item in messages if (item.get("info") or {}).get("role") == "assistant"]
            if assistants:
                last = assistants[-1]
                completed = ((last.get("info") or {}).get("time") or {}).get("completed")
                if completed:
                    text = _final_assistant_text(messages)
                    return _extract_final_json(text), session_id
            time.sleep(1)
        raise SkillResultError("OpenCode task timed out before producing a final JSON result.")
    finally:
        stop_event.set()
        stream_thread.join(timeout=2)
