from __future__ import annotations

from typing import Any, Protocol


class WorkflowTaskAdapter(Protocol):
    def get_task(self, task_id: int) -> dict[str, Any]: ...
    def get_session(self, task_id: int) -> dict[str, Any]: ...
    def get_context(self, task_id: int) -> dict[str, Any]: ...
    def get_current_plan(self, task_id: int) -> dict[str, Any] | None: ...
    def save_plan(self, task_id: int, plan: dict[str, Any]) -> dict[str, Any]: ...
